Repository Despereaux-MAU/team-musubi, pull requests merged in 2024-11, with the labels that each got.

#11 회원 탈퇴 기능 완성, Member Entity와 MemberDetailsImpl 분리
  src/main/java/com/musubi/teammusubi/common/Security/JwtAuthenticationFilter.java
  src/main/java/com/musubi/teammusubi/common/Security/JwtAuthorizationFilter.java
  src/main/java/com/musubi/teammusubi/common/Security/MemberDetailsImpl.java
  src/main/java/com/musubi/teammusubi/common/config/SecurityConfig.java
  src/main/java/com/musubi/teammusubi/common/entity/Member.java
  src/main/java/com/musubi/teammusubi/common/util/JwtUtil.java
  src/main/java/com/musubi/teammusubi/domain/member/controller/MemberController.java
  src/main/java/com/musubi/teammusubi/domain/member/repository/MemberRepository.java
  src/main/java/com/musubi/teammusubi/domain/member/service/MemberDetailsService.java
  src/main/java/com/musubi/teammusubi/domain/member/service/MemberDetailsServiceImpl.java
  src/main/java/com/musubi/teammusubi/domain/member/service/MemberService.java
Labels: bug

#27 7-customer-store-read-1
  api/musubi.postman_collection_customer_read.json
  src/main/java/com/musubi/teammusubi/common/entity/Delivery.java
  src/main/java/com/musubi/teammusubi/common/entity/DeliveryMenu.java
  src/main/java/com/musubi/teammusubi/domain/customer/controller/DeliveryController.java
  src/main/java/com/musubi/teammusubi/domain/customer/controller/StoreController.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/DeliveryResponse.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/OrderDeliveryRequest.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/StoreResponse.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/DeliveryRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/MenuRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/StoreRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/DeliveryService.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/StoreService.java
Labels: enhancement

#38 Seller#7 [FEAT] 사업자의 가게별 주문 조회
  api/project-outsourcing.postman_collection.json
  src/main/java/com/musubi/teammusubi/common/entity/Delivery.java
  src/main/java/com/musubi/teammusubi/domain/seller/controller/SellerStoreController.java
  src/main/java/com/musubi/teammusubi/domain/seller/repository/SellerDeliveryRepository.java
  src/main/java/com/musubi/teammusubi/domain/seller/repository/SellerStoreRepository.java
  src/main/java/com/musubi/teammusubi/domain/seller/service/SellerDeliveryService.java
  src/main/java/com/musubi/teammusubi/domain/seller/service/SellerStoreService.java
Labels: enhancement

#43 Seller#11 [REFACTOR] 사업자의 가게 메뉴 삭제
  src/main/java/com/musubi/teammusubi/common/entity/Delivery.java
  src/main/java/com/musubi/teammusubi/common/entity/Menu.java
  src/main/java/com/musubi/teammusubi/common/enums/MenuStatus.java
  src/main/java/com/musubi/teammusubi/domain/seller/controller/SellerMenuController.java
  src/main/java/com/musubi/teammusubi/domain/seller/dto/MenuRequest.java
  src/main/java/com/musubi/teammusubi/domain/seller/dto/MenuResponse.java
  src/main/java/com/musubi/teammusubi/domain/seller/service/SellerMenuService.java
Labels: modify

#48 32-customer #2 고객 입장에서의 주문 생성 및 가게 조회 기능 확장
  .gitignore
  api/jh.json
  src/main/java/com/musubi/teammusubi/common/entity/Delivery.java
  src/main/java/com/musubi/teammusubi/common/entity/DeliveryMenu.java
  src/main/java/com/musubi/teammusubi/common/entity/Store.java
  src/main/java/com/musubi/teammusubi/domain/customer/controller/DeliveryController.java
  src/main/java/com/musubi/teammusubi/domain/customer/controller/StoreController.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/DeliveryMenuResponse.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/DeliveryResponse.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/OrderDeliveryRequest.java
  src/main/java/com/musubi/teammusubi/domain/customer/dto/StoreResponse.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/DeliveryMenuRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/DeliveryRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/StoreRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/DeliveryService.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/StoreService.java
  src/main/java/com/musubi/teammusubi/domain/seller/dto/DeliveryResponse.java
Labels: enhancement

#54 32-customer-2 예외처리 강화, 버그 수정
  src/main/java/com/musubi/teammusubi/common/entity/DeliveryMenu.java
  src/main/java/com/musubi/teammusubi/common/exception/ExceptionType.java
  src/main/java/com/musubi/teammusubi/domain/customer/controller/DeliveryController.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/DeliveryRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/repository/StoreRepository.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/DeliveryService.java
  src/main/java/com/musubi/teammusubi/domain/customer/service/StoreService.java
Labels: bug, enhancement

#58 테스트 코드 작성 및 코드 정리
  src/main/java/com/musubi/teammusubi/common/entity/Menu.java
  src/main/java/com/musubi/teammusubi/common/entity/Store.java
  src/main/java/com/musubi/teammusubi/domain/seller/controller/SellerMenuController.java
  src/main/java/com/musubi/teammusubi/domain/seller/controller/SellerStoreController.java
  src/main/java/com/musubi/teammusubi/domain/seller/dto/MenuRequest.java
  src/main/java/com/musubi/teammusubi/domain/seller/service/SellerDeliveryService.java
  src/main/java/com/musubi/teammusubi/domain/seller/service/SellerMenuService.java
  src/test/java/com/musubi/teammusubi/seller/SellerDeliveryServiceTest.java
  src/test/java/com/musubi/teammusubi/seller/SellerMenuServiceTest.java
Labels: test

#61 테스트 코드 추가, JwtAuthenticationFilter 인증 정보 제거 기능 추가
  src/main/java/com/musubi/teammusubi/common/security/JwtAuthenticationFilter.java
  src/test/java/com/musubi/teammusubi/common/config/SecurityConfigTest.java
  src/test/java/com/musubi/teammusubi/common/security/JwtAuthenticationFilterTest.java
  src/test/java/com/musubi/teammusubi/common/security/JwtAuthorizationFilterTest.java
  src/test/java/com/musubi/teammusubi/domain/member/controller/MemberControllerTest.java
  src/test/java/com/musubi/teammusubi/domain/member/service/MemberServiceTest.java
Labels: test

#64 fix : MemberServiceTest authenticate 오류 수정
  src/test/java/com/musubi/teammusubi/domain/member/service/MemberServiceTest.java
Labels: test

#63 Test: Customer 테스트 코드 정상 부분 추가
  src/test/java/com/musubi/teammusubi/domain/customer/service/DeliveryServiceTest.java
  src/test/java/com/musubi/teammusubi/domain/customer/service/MenuServiceTest.java
  src/test/java/com/musubi/teammusubi/domain/customer/service/StoreServiceTest.java
Labels: enhancement
